### ISSUE TITLE
is --reseed.floodfill flag still available?

### ISSUE THREAD

**Issue by happywhitelake** [PurpleI2P/i2pd_docs_en#25]
https://github.com/PurpleI2P/i2pd_docs_en/blob/master/docs/user-guide/configuration.md
Verify .su3 signature. fase by default -> false

Is `--reseed.floodfill` flag still valid? It is shown on `--help` but not in the document?

**Comment by majestrate** [comment]
It should be, it was never removed.

Be warned though, you put ultimate trust in the floodfill you choose.

It can partition you into a slice of the network they control trivially.
