### ISSUE TITLE
"The file in keys must be present"

### ISSUE THREAD

**Issue by Vort** [PurpleI2P/i2pd_docs_en#73]
In documentation about Server/generic tunnels in this file:
https://github.com/PurpleI2P/i2pd_docs_en/blob/master/docs/user-guide/tunnels.md
_"The file in keys must be present"_ phrase exists.
From what I learned (_[18:06:47] <relaybot> i2porignal: если его нету то сделается_), if user do not put file at specified location, it will be automatically created, which makes me doubt about what "must be present" actually mean.
It it will be not present, then nothing wrong happens.

**Comment by r4sas** [comment]
Updated.
